id: W-05
name: 패스워드 최대 사용 기간 설정
category: 계정관리
severity: mid
description: |
  패스워드 최대 사용 기간을 90일 이하로 설정하여 정기적인 패스워드 변경을 유도합니다.

check:
  commands:
    - net accounts | findstr "Maximum password age"

validator: validators.windows.check_w05

remediation:
  auto: true
  description: 패스워드 최대 사용 기간을 90일로 설정합니다.
  backup_files: []
  commands:
    - net accounts /maxpwage:90

platforms:
  - windows

references:
  cis: "1.1.8"
  description: Maximum Password Age
