id: W-07
name: 계정 잠금 기간 설정
category: 계정관리
severity: mid
description: |
  계정 잠금 기간을 30분 이상으로 설정하여 무차별 대입 공격을 지연시킵니다.

check:
  commands:
    - net accounts | findstr "Lockout duration"

validator: validators.windows.check_w07

remediation:
  auto: true
  description: 계정 잠금 기간을 30분으로 설정합니다.
  backup_files: []
  commands:
    - net accounts /lockoutduration:30

platforms:
  - windows

references:
  cis: "1.2.2"
  description: Account Lockout Duration
