id: W-15
name: 원격 레지스트리 서비스 비활성화
category: 레지스트리
severity: medium
description: |
  원격 레지스트리 서비스를 비활성화하여 원격 레지스트리 접근을 차단합니다.
  RemoteRegistry 서비스의 Start 값이 4(Disabled)인지 확인합니다.
  원격 레지스트리 서비스는 공격자가 레지스트리를 원격으로 수정할 수 있게 합니다.

check:
  commands:
    - Get-ItemProperty -Path "HKLM:\System\CurrentControlSet\Services\RemoteRegistry" -Name "Start" | Select-Object -ExpandProperty Start

validator: validators.windows.check_w15

remediation:
  auto: true
  description: 원격 레지스트리 서비스를 비활성화합니다.
  backup_files: []
  commands:
    - Set-Service -Name "RemoteRegistry" -StartupType Disabled
    - Stop-Service -Name "RemoteRegistry" -Force

platforms:
  - windows

references:
  cis: "5.24"
  description: Ensure 'Remote Registry (RemoteRegistry)' is set to 'Disabled'
