id: W-18
name: SMB v1 프로토콜 비활성화
category: 레지스트리
severity: high
description: |
  SMB v1 프로토콜의 비활성화 여부를 확인합니다.
  SMB v1은 오래되고 취약한 프로토콜로 WannaCry 등 랜섬웨어 공격에 악용됩니다.
  SMB1 레지스트리 값이 0으로 설정되어야 안전한 SMB v2/v3만 사용됩니다.
  Microsoft는 2014년부터 SMB v1 사용 중단을 권고하고 있습니다.

check:
  commands:
    - Get-ItemProperty -Path "HKLM:\System\CurrentControlSet\Services\LanmanServer\Parameters" -Name "SMB1" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty SMB1

validator: validators.windows.check_w18

remediation:
  auto: true
  description: SMB v1 프로토콜을 비활성화합니다 (SMB1 = 0)
  backup_files: []
  commands:
    - Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Services\LanmanServer\Parameters" -Name "SMB1" -Value 0 -Type DWord

platforms:
  - windows

references:
  cis: "18.3.1"
  description: "SMBv1 client driver - Disable SMBv1 protocol"
