id: W-24
name: 스크린 세이버 패스워드 보호
category: 레지스트리
severity: medium
description: |
  스크린 세이버가 활성화될 때 패스워드 입력을 요구하여
  무단 접근을 방지합니다.
  ScreenSaverIsSecure 값이 1인지 확인합니다.

check:
  commands:
    - Get-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name "ScreenSaverIsSecure" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty ScreenSaverIsSecure

validator: validators.windows.check_w24

remediation:
  auto: true
  description: 스크린 세이버 패스워드 보호를 활성화합니다.
  backup_files: []
  commands:
    - Set-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name "ScreenSaverIsSecure" -Value 1

platforms:
  - windows

references:
  cis: "18.9.52.3.9.4"
  description: "Ensure 'Enable screen saver' and 'Password protect the screen saver' are set to 'Enabled'"
