id: W-26
name: Security 이벤트 로그 최대 크기
category: 레지스트리
severity: high
description: |
  Security 이벤트 로그의 최대 크기가 적절하게 설정되어 있는지 확인합니다.
  보안 이벤트는 시스템의 가장 중요한 감사 정보를 포함하므로,
  충분한 로그 크기(192 MB 이상)를 확보해야 합니다.

check:
  commands:
    - Get-ItemProperty -Path "HKLM:\Software\Policies\Microsoft\Windows\EventLog\Security" -Name "MaxSize" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty MaxSize

validator: validators.windows.check_w26

remediation:
  auto: true
  description: Security 이벤트 로그 최대 크기를 192 MB로 설정합니다.
  backup_files: []
  commands:
    - |
      if (-not (Test-Path "HKLM:\Software\Policies\Microsoft\Windows\EventLog\Security")) {
        New-Item -Path "HKLM:\Software\Policies\Microsoft\Windows\EventLog\Security" -Force
      }
      Set-ItemProperty -Path "HKLM:\Software\Policies\Microsoft\Windows\EventLog\Security" -Name "MaxSize" -Value 196608 -Type DWord

platforms:
  - windows

references:
  cis: "18.9.26.3.1"
  description: "Ensure 'Security' eventlog maximum log size is configured"
