id: W-27
name: Application 이벤트 로그 최대 크기
category: 레지스트리
severity: medium
description: |
  Application 이벤트 로그의 최대 크기가 적절하게 설정되어 있는지 확인합니다.
  애플리케이션 이벤트는 프로그램 실행 및 오류 정보를 포함하므로,
  충분한 로그 크기(32 MB 이상)를 확보해야 합니다.

check:
  commands:
    - Get-ItemProperty -Path "HKLM:\Software\Policies\Microsoft\Windows\EventLog\Application" -Name "MaxSize" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty MaxSize

validator: validators.windows.check_w27

remediation:
  auto: true
  description: Application 이벤트 로그 최대 크기를 32 MB로 설정합니다.
  backup_files: []
  commands:
    - |
      if (-not (Test-Path "HKLM:\Software\Policies\Microsoft\Windows\EventLog\Application")) {
        New-Item -Path "HKLM:\Software\Policies\Microsoft\Windows\EventLog\Application" -Force
      }
      Set-ItemProperty -Path "HKLM:\Software\Policies\Microsoft\Windows\EventLog\Application" -Name "MaxSize" -Value 32768 -Type DWord

platforms:
  - windows

references:
  cis: "18.9.26.1.1"
  description: "Ensure 'Application' eventlog maximum log size is configured"
