id: W-28
name: System 이벤트 로그 최대 크기
category: 레지스트리
severity: high
description: |
  System 이벤트 로그의 최대 크기가 적절하게 설정되어 있는지 확인합니다.
  시스템 이벤트는 운영체제의 핵심 정보를 포함하므로,
  충분한 로그 크기(32 MB 이상)를 확보해야 합니다.

check:
  commands:
    - Get-ItemProperty -Path "HKLM:\Software\Policies\Microsoft\Windows\EventLog\System" -Name "MaxSize" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty MaxSize

validator: validators.windows.check_w28

remediation:
  auto: true
  description: System 이벤트 로그 최대 크기를 32 MB로 설정합니다.
  backup_files: []
  commands:
    - |
      if (-not (Test-Path "HKLM:\Software\Policies\Microsoft\Windows\EventLog\System")) {
        New-Item -Path "HKLM:\Software\Policies\Microsoft\Windows\EventLog\System" -Force
      }
      Set-ItemProperty -Path "HKLM:\Software\Policies\Microsoft\Windows\EventLog\System" -Name "MaxSize" -Value 32768 -Type DWord

platforms:
  - windows

references:
  cis: "18.9.26.4.1"
  description: "Ensure 'System' eventlog maximum log size is configured"
