id: W-32
name: FTP 서비스 비활성화
category: 서비스 관리
severity: medium
description: |
  FTP 서비스가 비활성화되어 있는지 확인합니다.
  FTP는 암호화되지 않은 파일 전송 프로토콜로 보안 위험이 있습니다.
  SFTP 또는 FTPS 등 암호화된 대체 프로토콜을 사용해야 합니다.
  권장값은 4(Disabled)입니다.

check:
  commands:
    - Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\FTPSVC" -Name "Start" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Start

validator: validators.windows.check_w32

remediation:
  auto: true
  description: FTP 서비스를 비활성화합니다.
  backup_files: []
  commands:
    - Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\FTPSVC" -Name "Start" -Value 4 -Type DWord

platforms:
  - windows

references:
  cis: "5.15"
  description: "Ensure 'FTP Server' is set to 'Disabled' or 'Not Installed'"
