id: W-33
name: SNMP 서비스 비활성화
category: 서비스 관리
severity: medium
description: |
  SNMP 서비스가 비활성화되어 있는지 확인합니다.
  SNMP는 기본 커뮤니티 문자열이 평문으로 전송되어 보안 위험이 있습니다.
  필요한 경우 SNMPv3를 사용해야 하며, 불필요한 경우 비활성화해야 합니다.
  권장값은 4(Disabled)입니다.

check:
  commands:
    - Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\SNMP" -Name "Start" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Start

validator: validators.windows.check_w33

remediation:
  auto: true
  description: SNMP 서비스를 비활성화합니다.
  backup_files: []
  commands:
    - Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\SNMP" -Name "Start" -Value 4 -Type DWord

platforms:
  - windows

references:
  cis: "5.28"
  description: "Ensure 'SNMP Service' is set to 'Disabled' or 'Not Installed'"
