id: W-44
name: 드라이버 업데이트 제외 설정
category: 패치 관리
severity: low
description: |
  Windows Update에서 드라이버 업데이트를 제외하도록 설정되어 있는지 확인합니다.
  드라이버 자동 업데이트는 시스템 불안정을 야기할 수 있으므로,
  검증된 드라이버만 수동으로 설치하는 것을 권장합니다.
  ExcludeWUDriversInQualityUpdate 값이 1이면 드라이버 업데이트가 제외됩니다.

check:
  commands:
    - Get-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate" -Name "ExcludeWUDriversInQualityUpdate" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty ExcludeWUDriversInQualityUpdate

validator: validators.windows.check_w44

remediation:
  auto: true
  description: Windows Update에서 드라이버 자동 업데이트를 제외합니다.
  backup_files: []
  commands:
    - New-Item -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate" -Force -ErrorAction SilentlyContinue
    - Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate" -Name "ExcludeWUDriversInQualityUpdate" -Value 1 -Type DWord

platforms:
  - windows

references:
  cis: "18.9.101.2"
  description: "Ensure 'Do not include drivers with Windows Updates' is set to 'Enabled'"
