id: M-10
name: Firmware Password 설정
category: system_protection
severity: high
platforms:
  - macos

description: |
  Firmware Password는 Recovery Mode 및 외부 부팅을 방지합니다.
  물리적 접근을 통한 공격을 차단하는 핵심 보안 기능입니다.

check:
  commands:
    - sudo firmwarepasswd -check
  validator: validators.macos.check_m10

remediation:
  auto: false
  description: |
    Firmware Password는 Recovery Mode에서만 설정할 수 있습니다.
  manual_steps:
    - Recovery Mode로 재부팅 (Command+R)
    - Utilities > Firmware Password Utility
    - Turn On Firmware Password
    - 패스워드 설정 및 백업

education:
  risk_level: 높음
  attack_scenario: |
    Firmware Password가 없으면 공격자가 Recovery Mode로 부팅하여
    SIP를 비활성화하고 root 패스워드를 초기화할 수 있습니다.
  references:
    - https://support.apple.com/en-us/HT204455
