id: U-01
name: root 계정 원격 접속 제한
category: 계정관리
severity: high
description: root 계정 원격 접속 제한 취약점을 점검합니다.
check:
  commands:
  - cat /etc/inetd.conf
validator: validators.linux.check_u01
remediation:
  auto: false
  backup_files: []
  commands: []
platforms:
- linux
- macos
