id: U-02
name: 패스워드 복잡성 설정
category: 계정관리
severity: high
description: 패스워드 복잡성 설정 취약점을 점검합니다.
check:
  commands:
  - cat /etc/passwd | grep "ftp"
validator: validators.linux.check_u02
remediation:
  auto: false
  backup_files: []
  commands: []
platforms:
- linux
- macos
