id: U-04
name: 패스워드 파일 보호
category: 계정관리
severity: high
description: 패스워드 파일 보호 취약점을 점검합니다.
check:
  commands:
  - ls -al /var/spool/cron/crontabs/*
validator: validators.linux.check_u04
remediation:
  auto: false
  backup_files: []
  commands: []
platforms:
- linux
- macos
