id: U-05
name: root 이외의 UID가 '0' 금지
category: 계정관리
severity: mid
description: root 이외의 UID가 '0' 금지 취약점을 점검합니다.
check:
  commands:
  - cat /etc/xinetd.d/echo
validator: validators.linux.check_u05
remediation:
  auto: false
  backup_files: []
  commands: []
platforms:
- linux
- macos
