id: U-08
name: 패스워드 최대 사용기간 설정
category: 계정관리
severity: mid
description: 패스워드 최대 사용기간 설정 취약점을 점검합니다.
check:
  commands:
  - ps -ef | grep automount
validator: validators.linux.check_u08
remediation:
  auto: false
  backup_files: []
  commands: []
