id: U-09
name: 패스워드 최소 사용기간 설정
category: 계정관리
severity: mid
description: 패스워드 최소 사용기간 설정 취약점을 점검합니다.
check:
  commands:
  - ps -ef | egrep "rpc.*|sadmind|walld|rusersd|rstatd|rexd|kcms_server|cachefsd"
validator: validators.linux.check_u09
remediation:
  auto: false
  backup_files: []
  commands: []
