id: U-11
name: 관리자 그룹에 최소한의 계정 포함
category: 계정관리
severity: low
description: 관리자 그룹에 최소한의 계정 포함 취약점을 점검합니다.
check:
  commands:
  - ps -ef | egrep "tftp|talk"
validator: validators.linux.check_u11
remediation:
  auto: false
  backup_files: []
  commands: []
