id: U-12
name: 계정이 존재하지 않는 GID 금지
category: 계정관리
severity: low
description: 계정이 존재하지 않는 GID 금지 취약점을 점검합니다.
check:
  commands:
  - ps -ef | grep sendmail
validator: validators.linux.check_u12
remediation:
  auto: false
  backup_files: []
  commands: []
platforms:
- linux
- macos
