id: U-13
name: 동일한 UID 금지
category: 계정관리
severity: mid
description: 동일한 UID 금지 취약점을 점검합니다.
check:
  commands:
  - ps -ef | grep sendmail | grep -v "grep"
validator: validators.linux.check_u13
remediation:
  auto: false
  backup_files: []
  commands: []
