id: U-15
name: Session Timeout 설정
category: 계정관리
severity: low
description: Session Timeout 설정 취약점을 점검합니다.
check:
  commands:
  - ps -ef | grep named
validator: validators.linux.check_u15
remediation:
  auto: false
  backup_files: []
  commands: []
platforms:
- linux
- macos
