id: U-16
name: root 홈, 패스 디렉터리 권한 및 패스 설정
category: 파일 및 디렉터리 관리
severity: high
description: root 홈, 패스 디렉터리 권한 및 패스 설정 취약점을 점검합니다.
check:
  commands:
  - ps -ef | grep named | grep -v "grep"
validator: validators.linux.check_u16
remediation:
  auto: false
  backup_files: []
  commands: []
