id: U-17
name: 파일 및 디렉터리 소유자 설정
category: 파일 및 디렉터리 관리
severity: high
description: 파일 및 디렉터리 소유자 설정 취약점을 점검합니다.
check:
  commands:
  - cat $APACHE_DIRECTORY/conf/httpd.conf | grep "Indexes"
validator: validators.linux.check_u17
remediation:
  auto: false
  backup_files: []
  commands: []
