id: U-18
name: /etc/passwd 파일 소유자 및 권한 설정
category: 파일 및 디렉터리 관리
severity: high
description: /etc/passwd 파일 소유자 및 권한 설정 취약점을 점검합니다.
check:
  commands:
  - ls -l /etc/passwd
validator: validators.linux.check_u18
remediation:
  auto: true
  description: /etc/passwd 파일 권한을 600 (rw-------)으로 설정합니다.
  backup_files:
  - /etc/passwd
  commands:
  - chmod 600 /etc/passwd
platforms:
- linux
- macos
