id: U-18
name: /etc/passwd 파일 소유자 및 권한 설정
category: 파일 및 디렉터리 관리
severity: high
description: /etc/passwd 파일 소유자 및 권한 설정 취약점을 점검합니다.
check:
  commands:
  - cat $APACHE_DIRECTORY/conf/httpd.conf | egrep "User|Group"
validator: validators.linux.check_u18
remediation:
  auto: false
  backup_files: []
  commands: []
