# U-18: 소유자 없는 파일 및 디렉토리 관리
# KISA 주요정보통신기반시설 기술적 취약점 분석평가 기준

# 메타데이터
id: "U-18"
name: "소유자 없는 파일 및 디렉토리 관리"
category: "파일 및 디렉토리 관리"
severity: "high"
kisa_standard: "U-18"

# 설명
description: |
  소유자가 없는 파일이나 디렉토리가 존재하는지 점검합니다.
  소유자 없는 파일은 보안 위협이 될 수 있습니다.

  취약점:
  - 삭제된 사용자의 파일이 남아있을 수 있음
  - 공격자가 해당 UID/GID를 재사용하면 파일 접근 가능
  - 시스템 무결성 침해 가능

  조치:
  - 소유자 없는 파일 목록 작성
  - 필요한 파일은 적절한 소유자 할당
  - 불필요한 파일은 삭제

# 점검 명령어
commands:
  - "find / -nouser -o -nogroup 2>/dev/null | head -20"

# Validator 함수
validator: "validators.linux.check_u18_orphan_files"

# 기대 결과
expected_result: |
  소유자 없는 파일이 없거나,
  필요 시 적절한 소유자가 할당되어 있어야 함

# 자동 수정 정보
remediation:
  auto: true
  backup_files: []
  commands:
    - "# 발견된 파일에 대해 chown root:root <파일경로>"
    - "# 또는 rm -f <파일경로> (불필요한 파일)"
  manual_steps:
    - "소유자 없는 파일 목록 확인"
    - "각 파일의 용도 파악 후 적절한 소유자 할당"
    - "불필요한 파일은 삭제"
    - "중요 파일은 백업 후 작업"
