id: U-19
name: /etc/shadow 파일 소유자 및 권한 설정
category: 파일 및 디렉터리 관리
severity: high
description: /etc/shadow 파일 소유자 및 권한 설정 취약점을 점검합니다.
check:
  commands:
  - ls -l /etc/shadow
validator: validators.linux.check_u19
remediation:
  auto: true
  description: /etc/shadow 파일 권한을 400 (r--------)으로 설정합니다.
  backup_files:
  - /etc/shadow
  commands:
  - chmod 400 /etc/shadow
platforms:
- linux
- macos
