id: U-20
name: /etc/hosts 파일 소유자 및 권한 설정
category: 파일 및 디렉터리 관리
severity: high
description: /etc/hosts 파일 소유자 및 권한 설정 취약점을 점검합니다.
check:
  commands:
  - ls -ld $APACHE_DIRECTORY/htdocs/manual
validator: validators.linux.check_u20
remediation:
  auto: false
  backup_files: []
  commands: []
platforms:
- linux
- macos
