id: U-21
name: /etc/(x)inetd.conf 파일 소유자 및 권한 설정
category: 파일 및 디렉터리 관리
severity: high
description: /etc/(x)inetd.conf 파일 소유자 및 권한 설정 취약점을 점검합니다.
check:
  commands:
  - ls -l /etc/inetd.conf
validator: validators.linux.check_u21
remediation:
  auto: true
  description: /etc/inetd.conf 파일 권한을 600 (rw-------)으로 설정합니다.
  backup_files:
  - /etc/inetd.conf
  commands:
  - chmod 600 /etc/inetd.conf
