id: U-22
name: /etc/syslog.conf 파일 소유자 및 권한 설정
category: 파일 및 디렉터리 관리
severity: high
description: /etc/syslog.conf 파일 소유자 및 권한 설정 취약점을 점검합니다.
check:
  commands:
  - ls -l /etc/syslog.conf
validator: validators.linux.check_u22
remediation:
  auto: true
  description: /etc/syslog.conf 파일 권한을 644 (rw-r--r--)로 설정합니다.
  backup_files:
  - /etc/syslog.conf
  commands:
  - chmod 644 /etc/syslog.conf
