id: U-22
name: /etc/syslog.conf 파일 소유자 및 권한 설정
category: 파일 및 디렉터리 관리
severity: high
description: /etc/syslog.conf 파일 소유자 및 권한 설정 취약점을 점검합니다.
check:
  commands:
  - cat $APACHE_DIRECTORY/conf/httpd.conf | grep LimitRequestBody
validator: validators.linux.check_u22
remediation:
  auto: false
  backup_files: []
  commands: []
