id: U-23
name: /etc/services 파일 소유자 및 권한 설정
category: 파일 및 디렉터리 관리
severity: high
description: /etc/services 파일 소유자 및 권한 설정 취약점을 점검합니다.
check:
  commands:
  - ls -l /etc/services
validator: validators.linux.check_u23
remediation:
  auto: true
  description: /etc/services 파일 권한을 644 (rw-r--r--)로 설정합니다.
  backup_files:
  - /etc/services
  commands:
  - chmod 644 /etc/services
platforms:
- linux
- macos
