id: U-25
name: 사용자, 시스템 시작파일 및 환경파일 소유자 및 권한 설정
category: 파일 및 디렉터리 관리
severity: high
description: 사용자, 시스템 시작파일 및 환경파일 소유자 및 권한 설정 취약점을 점검합니다.
check:
  commands:
  - ps -ef | grep ftp
validator: validators.linux.check_u25
remediation:
  auto: false
  backup_files: []
  commands: []
