id: U-27
name: /dev에 존재하지 않는 device 파일 점검
category: 파일 및 디렉터리 관리
severity: high
description: /dev에 존재하지 않는 device 파일 점검 취약점을 점검합니다.
check:
  commands:
  - ls -al /etc/ftpusers
validator: validators.linux.check_u27
remediation:
  auto: false
  backup_files: []
  commands: []
platforms:
- linux
- macos
