id: U-28
name: $HOME/.rhosts, hosts.equiv 사용 금지
category: 파일 및 디렉터리 관리
severity: high
description: $HOME/.rhosts, hosts.equiv 사용 금지 취약점을 점검합니다.
check:
  commands:
  - cat /etc/ftpd/ftpusers
validator: validators.linux.check_u28
remediation:
  auto: false
  backup_files: []
  commands: []
