id: U-29
name: 접속 IP 및 포트 제한
category: 파일 및 디렉터리 관리
severity: high
description: 접속 IP 및 포트 제한 취약점을 점검합니다.
check:
  commands:
  - ls -l /etc/at.allow
validator: validators.linux.check_u29
remediation:
  auto: false
  backup_files: []
  commands: []
platforms:
- linux
- macos
