id: U-32
name: UMASK 설정 관리
category: 파일 및 디렉터리 관리
severity: mid
description: UMASK 설정 관리 취약점을 점검합니다.
check:
  commands:
  - cat /etc/motd
validator: validators.linux.check_u32
remediation:
  auto: false
  backup_files: []
  commands: []
platforms:
- linux
- macos
