id: U-33
name: 홈 디렉토리 소유자 및 권한 설정
category: 파일 및 디렉터리 관리
severity: mid
description: 홈 디렉토리 소유자 및 권한 설정 취약점을 점검합니다.
check:
  commands:
  - cat ls -al /etc/exports
validator: validators.linux.check_u33
remediation:
  auto: false
  backup_files: []
  commands: []
