id: U-34
name: 홈 디렉토리로 지정한 디렉터리의 존재 관리
category: 파일 및 디렉터리 관리
severity: mid
description: 홈 디렉토리로 지정한 디렉터리의 존재 관리 취약점을 점검합니다.
check:
  commands:
  - cat /etc/mail/sendmail.cf | grep PrivacyOptions
validator: validators.linux.check_u34
remediation:
  auto: false
  backup_files: []
  commands: []
