id: U-38
name: r계열 서비스 비활성화
category: 서비스 관리
severity: high
description: r계열 서비스 비활성화 취약점을 점검합니다.
check:
  commands:
  - cat /etc/inetd.conf | grep -E "rsh|rlogin|rexec"
  - cat /etc/xinetd.d/rsh
validator: validators.linux.check_u38
remediation:
  auto: true
  description: r계열 서비스(rsh, rlogin, rexec)를 비활성화합니다.
  backup_files:
  - /etc/inetd.conf
  commands:
  - sed -i 's/^rsh/#rsh/' /etc/inetd.conf 2>/dev/null || true
  - sed -i 's/^rlogin/#rlogin/' /etc/inetd.conf 2>/dev/null || true
  - sed -i 's/^rexec/#rexec/' /etc/inetd.conf 2>/dev/null || true
platforms:
- linux
- macos
