id: U-39
name: cron 파일 소유자 및 권한 설정
category: 서비스 관리
severity: high
description: cron 파일 소유자 및 권한 설정 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u39
remediation:
  auto: false
  backup_files: []
  commands: []
