id: U-39
name: cron 파일 소유자 및 권한 설정
category: 서비스 관리
severity: high
description: cron 파일 소유자 및 권한 설정 취약점을 점검합니다.
check:
  commands:
  - ls -al /var/spool/cron/crontabs/*
  - ls -al /etc/crontab
validator: validators.linux.check_u39
remediation:
  auto: true
  description: cron 파일 권한을 640 (rw-r-----)으로 설정합니다.
  backup_files:
  - /etc/crontab
  - /var/spool/cron/crontabs
  commands:
  - chmod 640 /etc/crontab
  - chmod 640 /var/spool/cron/crontabs/* 2>/dev/null || true
platforms:
- linux
- macos
