id: U-41
name: NFS 서비스 비활성화
category: 서비스 관리
severity: high
description: NFS 서비스 비활성화 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u41
remediation:
  auto: false
  backup_files: []
  commands: []
