id: U-42
name: NFS 접근 통제
category: 서비스 관리
severity: high
description: NFS 접근 통제 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u42
remediation:
  auto: false
  backup_files: []
  commands: []
