id: U-43
name: automountd 제거
category: 서비스 관리
severity: high
description: automountd 제거 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u43
remediation:
  auto: false
  backup_files: []
  commands: []
