id: U-45
name: NIS, NIS+ 점검
category: 서비스 관리
severity: high
description: NIS, NIS+ 점검 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u45
remediation:
  auto: false
  backup_files: []
  commands: []
