id: U-46
name: tftp, talk 서비스 비활성화
category: 서비스 관리
severity: high
description: tftp, talk 서비스 비활성화 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u46
remediation:
  auto: false
  backup_files: []
  commands: []
platforms:
- linux
- macos
