id: U-50
name: DNS 보안 버전 패치
category: 서비스 관리
severity: high
description: DNS 보안 버전 패치 취약점을 점검합니다.
check:
  commands:
    - named -v
    - rpm -qa bind
validator: validators.linux.check_u50
remediation:
  auto: false
  backup_files: []
  commands: []
