id: U-51
name: DNS Zone Transfer 설정
category: 서비스 관리
severity: high
description: DNS Zone Transfer 설정 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u51
remediation:
  auto: false
  backup_files: []
  commands: []
