id: U-52
name: Apache 디렉터리 리스팅 제거
category: 서비스 관리
severity: high
description: Apache 디렉터리 리스팅 제거 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u52
remediation:
  auto: false
  backup_files: []
  commands: []
