id: U-53
name: Apache 웹 프로세스 권한 제한
category: 서비스 관리
severity: high
description: Apache 웹 프로세스 권한 제한 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u53
remediation:
  auto: false
  backup_files: []
  commands: []
