id: U-54
name: Apache 상위 디렉터리 접근 금지
category: 서비스 관리
severity: high
description: Apache 상위 디렉터리 접근 금지 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u54
remediation:
  auto: false
  backup_files: []
  commands: []
