id: U-57
name: Apache 파일 업로드 및 다운로드 제한
category: 서비스 관리
severity: high
description: Apache 파일 업로드 및 다운로드 제한 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u57
remediation:
  auto: false
  backup_files: []
  commands: []
