id: U-58
name: Apache 웹 서비스 영역의 분리
category: 서비스 관리
severity: high
description: Apache 웹 서비스 영역의 분리 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u58
remediation:
  auto: false
  backup_files: []
  commands: []
