id: U-59
name: ssh 원격접속 허용
category: 서비스 관리
severity: mid
description: ssh 원격접속 허용 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u59
remediation:
  auto: false
  backup_files: []
  commands: []
