id: U-61
name: ftp 계정 shell 제한
category: 서비스 관리
severity: mid
description: ftp 계정 shell 제한 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u61
remediation:
  auto: false
  backup_files: []
  commands: []
