id: U-62
name: ftpusers 파일 소유자 및 권한 설정
category: 서비스 관리
severity: low
description: ftpusers 파일 소유자 및 권한 설정 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u62
remediation:
  auto: false
  backup_files: []
  commands: []
