id: U-63
name: ftpusers 파일 설정
category: 서비스 관리
severity: mid
description: ftpusers 파일 설정 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u63
remediation:
  auto: false
  backup_files: []
  commands: []
