id: U-64
name: at 파일 소유자 및 권한 설정
category: 서비스 관리
severity: mid
description: at 파일 소유자 및 권한 설정 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u64
remediation:
  auto: false
  backup_files: []
  commands: []
