id: U-65
name: SNMP 서비스 구동 점검
category: 서비스 관리
severity: mid
description: SNMP 서비스 구동 점검 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u65
remediation:
  auto: false
  backup_files: []
  commands: []
