id: U-66
name: SNMP 서비스 Community String의 복잡성
category: 서비스 관리
severity: mid
description: SNMP 서비스 Community String의 복잡성 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u66
remediation:
  auto: false
  backup_files: []
  commands: []
