id: U-69
name: expn, vrfy 명령어 제한
category: 서비스 관리
severity: mid
description: expn, vrfy 명령어 제한 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u69
remediation:
  auto: false
  backup_files: []
  commands: []
