id: U-70
name: Apache 웹서비스 정보 숨김
category: 서비스 관리
severity: mid
description: Apache 웹서비스 정보 숨김 취약점을 점검합니다.
check:
  commands:
    - cat /etc/httpd/conf/httpd.conf
    - cat /etc/apache2/apache2.conf
validator: validators.linux.check_u70
remediation:
  auto: false
  backup_files: []
  commands: []
