id: U-72
name: 로그의 정기적 검토 및 보고
category: 로그 관리
severity: high
description: 로그의 정기적 검토 및 보고 취약점을 점검합니다.
check:
  commands: []
validator: validators.linux.check_u72
remediation:
  auto: false
  backup_files: []
  commands: []
