id: U-73
name: 로그 기록 정책 수립
category: 로그 관리
severity: low
description: 로그 기록 정책 수립 취약점을 점검합니다.
check:
  commands:
    - cat /etc/rsyslog.conf
    - cat /etc/syslog.conf
validator: validators.linux.check_u73
remediation:
  auto: false
  backup_files: []
  commands: []
